name: popover_example
description: Popover Example.
version: 0.0.2
publish_to: none

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

  popover_gtk:
    path: ../

dev_dependencies:
  flutter_test:
    sdk: flutter
