name: popover_gtk
description: A popover made to be used with libadwaita library, Includes fade animation instead of scale.
version: 0.2.6+3
homepage: https://github.com/minikin/popover

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=2.0.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter
